# Generated by Django 5.2.1 on 2025-06-01 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название диска', max_length=100, unique=True)),
                ('api_type', models.CharField(choices=[('webdav', 'webdav')], max_length=100)),
                ('credentials', models.JSONField(blank=True, help_text='Учетные данные', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cloud Storage',
                'verbose_name_plural': 'Cloud Storages',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField(max_length=500, unique=True, verbose_name='путь к источнику')),
                ('status', models.CharField(choices=[('cr', 'Создан'), ('sy', 'Синхронизирован'), ('pa', 'Обработан'), ('ch', 'Разбит на чанки'), ('em', 'Эмбеддинг выполнен'), ('ad', 'Добавлен в базу знаний'), ('de', 'Удален'), ('er', 'Ошибка')], default='cr', max_length=2, verbose_name='статус обработки')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='язык документа')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='наименование документа')),
                ('categories', models.JSONField(default=list, help_text="Категории в формате JSON, например ['news', 'tech', ]", verbose_name='список тегов')),
                ('error_message', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ошибка при обрабоотке')),
                ('metadata', models.JSONField(default=dict, help_text='Хранит API-специфичные данные (например, fileId для Google Drive)', verbose_name='дополнительные метаданные')),
                ('remote_updated', models.DateTimeField(blank=True, null=True, verbose_name='дата обновления в источнике')),
                ('local_updated', models.DateTimeField(blank=True, null=True, verbose_name='дата обновления в проекте')),
                ('synchronized_at', models.DateTimeField(blank=True, null=True, verbose_name='дата синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP-код ответа', null=True)),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField(max_length=500, unique=True, verbose_name='путь к источнику')),
                ('status', models.CharField(choices=[('cr', 'Создан'), ('sy', 'Синхронизирован'), ('pa', 'Обработан'), ('ch', 'Разбит на чанки'), ('em', 'Эмбеддинг выполнен'), ('ad', 'Добавлен в базу знаний'), ('de', 'Удален'), ('er', 'Ошибка')], default='cr', max_length=2, verbose_name='статус обработки')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='язык документа')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='наименование документа')),
                ('categories', models.JSONField(default=list, help_text="Категории в формате JSON, например ['news', 'tech', ]", verbose_name='список тегов')),
                ('error_message', models.CharField(blank=True, max_length=1000, null=True, verbose_name='ошибка при обрабоотке')),
                ('metadata', models.JSONField(default=dict, help_text='Хранит API-специфичные данные (например, fileId для Google Drive)', verbose_name='дополнительные метаданные')),
                ('remote_updated', models.DateTimeField(blank=True, null=True, verbose_name='дата обновления в источнике')),
                ('local_updated', models.DateTimeField(blank=True, null=True, verbose_name='дата обновления в проекте')),
                ('synchronized_at', models.DateTimeField(blank=True, null=True, verbose_name='дата синхронизации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('description', models.TextField(blank=True, help_text='Краткое описание', null=True)),
                ('cloud_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app_sources.cloudstorage')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
