from .recognizer_classes.docx_recognizer import DOCXRecognizer
from .recognizer_classes.image_recognizer import ImageRecognizer
from .recognizer_classes.pdf_recognizer import PDFRecognizer
from .registry import register_recognizer


register_recognizer(PDFRecognizer)
register_recognizer(DOCXRecognizer)
register_recognizer(ImageRecognizer)